allowBuilds:
    esbuild: true
    msgpackr-extract: true
    unrs-resolver: true
minimumReleaseAge: 1440
overrides:
    seroval: ^1.5.4
    seroval-plugins: ^1.5.4
trustPolicy: no-downgrade
trustPolicyExclude:
    - '@effect/platform-node-shared@4.0.0-beta.70'
    - effect@4.0.0-beta.70
    - semver@6.3.1
minimumReleaseAgeExclude:
    - eslint@10.5.0
    - '@tailwindcss/node@4.3.1'
    - '@tailwindcss/oxide-android-arm64@4.3.1'
    - '@tailwindcss/oxide-darwin-arm64@4.3.1'
    - '@tailwindcss/oxide-darwin-x64@4.3.1'
    - '@tailwindcss/oxide-freebsd-x64@4.3.1'
    - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.1'
    - '@tailwindcss/oxide-linux-arm64-gnu@4.3.1'
    - '@tailwindcss/oxide-linux-arm64-musl@4.3.1'
    - '@tailwindcss/oxide-linux-x64-gnu@4.3.1'
    - '@tailwindcss/oxide-linux-x64-musl@4.3.1'
    - '@tailwindcss/oxide-wasm32-wasi@4.3.1'
    - '@tailwindcss/oxide-win32-arm64-msvc@4.3.1'
    - '@tailwindcss/oxide-win32-x64-msvc@4.3.1'
    - '@tailwindcss/oxide@4.3.1'
    - '@tailwindcss/vite@4.3.1'
    - lucide-react@1.18.0
    - tailwindcss@4.3.1
onlyBuiltDependencies:
    - esbuild
    - unrs-resolver
